controller_list:
  - name: gummi_right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_yaw
      - shoulder_roll
      - shoulder_pitch
      - upperarm_roll
      - elbow
      - wrist_pitch
      - forearm_roll
  # - name: fake_right_gripper_controller
    # joints:
      # - gripper
