calibrated: 1
equilibrium:
    sign: -1
    signFlexor: -1
    signExtensor: 1
    nameFlexor: "shoulder_flexor"
    nameExtensor: "shoulder_extensor"
    servoRange: 12.5664
    servoOffset: 2
    loadLimit: 0.5  # Testing limitLoad method in equilibrium_model.py.
signEncoder: 1
signJoint: 1
name: "shoulder_roll"
nameEncoder: "shoulder_roll_encoder"
minAngle: -1.6
maxAngle: 0.9
maxAbsForwardError: 0.6
gains:
    P: 0.025
    I: 0.00002
    D: 0.1
restingPoseAngle: -0.2 # Parameter to adjusting resting pose joint angle.
